name: 'Start or Stop a prefect flow'
description: 'Start or Stop a group of Flows based on their tag'
inputs:
  prefect_account_key: 
    description: 'PREFECT_ACCOUNT_KEY'
    required: true
    default: ''
  action: 
    description: 'action to take (stop|start)'
    required: true
    default: ''
  branch: 
    description: 'branch to look for'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.mjs'
